services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
       - ${ENV_FILE:-.env}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - tech-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
       - ${ENV_FILE:-.env}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 10s
    networks:
      - tech-network

  newrelic-infra:
    image: newrelic/infrastructure:latest
    container_name: newrelic-infra
    privileged: true
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
    env_file:
       - ${ENV_FILE:-.env}
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  tech-network:
    driver: bridge
