[tool:pytest]
asyncio_mode = auto
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::DeprecationWarning:pydantic.*
    ignore::DeprecationWarning:datetime.*
    ignore::DeprecationWarning
    ignore:Support for class-based.*:DeprecationWarning
    ignore:Using extra keyword arguments.*:DeprecationWarning
    ignore:Pydantic V1 style.*:DeprecationWarning
    ignore:The `dict` method is deprecated.*:DeprecationWarning
    ignore:datetime.datetime.utcnow.*:DeprecationWarning
