apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secret
  namespace: tech-challenge
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME_IN_CI"
  MYSQL_PASSWORD: "CHANGE_ME_IN_CI"
  # Se preferir injetar URLs prontas:
  DATABASE_URL: "mysql+aiomysql://tech_user:CHANGE_ME@mysql:3306/tech_challenge"
  MIGRATION_DATABASE_URL: "mysql+pymysql://tech_user:CHANGE_ME@mysql:3306/tech_challenge"
