"""Initial migration - create products table

Revision ID: 001_initial
Revises: 
Create Date: 2025-01-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import CHAR

# revision identifiers, used by Alembic.
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
        sa.Column('id', CHAR(36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('stock', sa.Integer(), nullable=False),
        sa.Column('image', sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Insert initial data
    op.execute("""
        INSERT INTO products (id, name, description, price, stock, image) VALUES 
        ('3f996431-e90e-4d12-b2be-5614959c0202', 'milk', 'skimmed cows milk', 10.50, 1, 'milk.jpg'),
        ('3f996431-e90e-4d12-b2be-5614959c0201', 'meat', 'beef licence', 20.50, 2, 'meat.jpg')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
