"""Create clientes table

Revision ID: 002_create_clientes
Revises: 001_initial
Create Date: 2025-07-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '002_create_clientes'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('cpf', sa.String(length=14), nullable=True),
        sa.Column('criado_em', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('atualizado_em', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Insert initial data
    op.execute("""
        INSERT INTO clientes (nome, telefone, email, cpf) VALUES 
        ('João Silva', '(11) 99999-1234', 'joao.silva@email.com', '123.456.789-01'),
        ('Maria Santos', '(11) 88888-5678', 'maria.santos@email.com', '987.654.321-02'),
        ('Pedro Oliveira', '(11) 77777-9012', 'pedro.oliveira@email.com', '456.789.123-03'),
        ('Ana Costa', '(11) 66666-3456', 'ana.costa@email.com', '789.123.456-04'),
        ('Carlos Ferreira', '(11) 55555-7890', 'carlos.ferreira@email.com', '321.654.987-05')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
