"""Create servicos table

Revision ID: 003_create_servicos
Revises: 002_create_clientes
Create Date: 2025-07-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '002_create_servicos'
down_revision = '001_create_clientes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicos',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('descricao', sa.String(length=255), nullable=False),
        sa.Column('preco', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Insert initial data
    op.execute("""
        INSERT INTO servicos (descricao, preco) VALUES 
        ('Troca de Óleo', 50.00),
        ('Alinhamento de Direção', 50.00),
        ('Manutenção do Freio', 200.00),
        ('Revisão', 250.00),
        ('Troca de Pneus', 60.00)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicos')
    # ### end Alembic commands ###
