"""create ordens_servico and association table

Revision ID: c436821072a4
Revises: 5c689865e085
Create Date: 2025-08-08 11:07:43.259429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c436821072a4'
down_revision = '5c689865e085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_servico',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.String(length=36), nullable=True),
    sa.Column('atendente_id', sa.String(length=36), nullable=True),
    sa.Column('orcamento_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.String(length=36), nullable=False),
    sa.Column('servico_id', sa.String(length=36), nullable=False),
    sa.Column('valor_servico', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordem_servico_servico')
    op.drop_table('ordens_servico')
    # ### end Alembic commands ###
