apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-deployment
  namespace: tech-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      # SecurityContext do POD (ok aqui)
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      containers:
        - name: tech-challenge
          image: your-docker-registry/tech-challenge:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: tech-challenge-config
            - secretRef:
                name: tech-challenge-secret
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
